/**
 * Missing default colors for the UI.
 */
export const missingDefaultColors = {
	"activityBar.background": "#333333",
	"activityBar.dropBackground": "#585858",
	"activityBar.foreground": "#ADADAD",
	"activityBarBadge.background": "#297FC9",
	"activityBarBadge.foreground": "#FFFFFF",
	"button.background": "#297FC9",
	"button.foreground": "#FFFFFF",
	"button.hoverBackground": "#2F7AB8",
	"debugExceptionWidget.background": "#3C2120",
	"debugExceptionWidget.border": "#3C2120",
	"debugToolBar.background": "#333333",
	"diffEditor.insertedTextBackground": "#3B3E2b",
	"diffEditor.insertedTextBorder": "#4E5433",
	"diffEditor.removedTextBackground": "#471F1D",
	"diffEditor.removedTextBorder": "#651F1C",
	"dropdown.background": "#3C3C3C",
	"dropdown.foreground": "#FFFFFF",
	"editor.findMatchBackground": "#535C69",
	"editor.findMatchHighlightBackground": "#4B382C",
	"editor.hoverHighlightBackground": "#404040",
	"editor.inactiveSelectionBackground": "#27394C",
	"editor.selectionBackground": "#2D5176",
	"editor.selectionHighlightBackground": "#282E32",
	"editorCursor.foreground": "#AEAFAD",
	"editorHoverWidget.background": "#1E1E1E",
	"editorHoverWidget.border": "#404040",
	"editorIndentGuide.background": "#404040",
	"editorLineNumber.foreground": "#404040",
	"editorSuggestWidget.background": "#1E1E1E",
	"editorSuggestWidget.border": "#404040",
	"editorSuggestWidget.foreground": "#D4D4D4",
	"editorSuggestWidget.highlightForeground": "#FFFFFF",
	"editorSuggestWidget.selectedBackground": "#2D5176",
	"editorWhitespace.foreground": "#404040",
	"editorWidget.background": "#404040",
	"input.background": "#404040",
	"input.foreground": "#D4D4D4",
	"inputValidation.errorBorder": "#3C2120",
	"list.dropBackground": "#383B3D",
	"sideBar.background": "#1E1E1E",
	"sideBarTitle.foreground": "#BBBBBB"
};
